name: readzs_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.1
  - python=3.9.6
  - pandas=1.3.1
  - pysam=0.16.0.1
  - nextflow=21.04.0
  - bioconda::picard=2.26.2
  - bioconda::bedtools=2.30.0
  - bioconda::samtools=1.13
  - bioconda::bioconductor-gviz=1.36.1


